version: "3"
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "5900:5900"
  app:
    build: .
    container_name: app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
